feed_location: /home/joshua/test/test.xml
feed_title: NHK Easy
feed_id: www.jmoravec.ddns.net
feed_xml:  <?xml version="1.0" encoding="utf-8"?>
nhk_main: http://www3.nhk.or.jp/news/easy/index.html
nhk_json: http://www3.nhk.or.jp/news/easy/news-list.json
